Compose:
  CompositionLocalAllowlist:
    active: false
  ContentEmitterReturningValues:
    active: true
  DefaultsVisibility:
    active: true
  ModifierComposable:
    active: true
  ModifierMissing:
    active: true
  ModifierNaming:
    active: true
  ModifierNotUsedAtRoot:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
  MutableParams:
    active: true
  ComposableNaming:
    active: true
  ComposableParamOrder:
    active: true
  PreviewAnnotationNaming:
    active: false
  PreviewPublic:
    active: true
  RememberMissing:
    active: true
  UnstableCollections:
    active: false
  ViewModelForwarding:
    active: true
  ViewModelInjection:
    active: true
