build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

processors:
  active: false

output-reports:
  active: true

comments:
  active: false
  AbsentOrWrongFileLicense:
    active: false
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  DeprecatedBlockTag:
    active: false
  EndOfSentenceFormat:
    active: false
  KDocReferencesNonPublicProperty:
    active: false
  OutdatedDocumentation:
    active: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

complexity:
  active: false
  ComplexCondition:
    active: false
  ComplexInterface:
    active: false
  CyclomaticComplexMethod:
    active: false
  LabeledExpression:
    active: false
  LargeClass:
    active: false
  LongMethod:
    active: false
  LongParameterList:
    active: false
  MethodOverloading:
    active: false
  NamedArguments:
    active: false
  NestedBlockDepth:
    active: true
    threshold: 4
  NestedScopeFunctions:
    active: false
  ReplaceSafeCallChainWithRun:
    active: false
  StringLiteralDuplication:
    active: false
  TooManyFunctions:
    active: false

coroutines:
  active: false
  GlobalCoroutineUsage:
    active: false
  InjectDispatcher:
    active: false
  RedundantSuspendModifier:
    active: false
  SleepInsteadOfDelay:
    active: false
  SuspendFunWithCoroutineScopeReceiver:
    active: false
  SuspendFunWithFlowReturnType:
    active: false

empty-blocks:
  active: false
  EmptyCatchBlock:
    active: false
  EmptyClassBlock:
    active: false
  EmptyDefaultConstructor:
    active: false
  EmptyDoWhileBlock:
    active: false
  EmptyElseBlock:
    active: false
  EmptyFinallyBlock:
    active: false
  EmptyForBlock:
    active: false
  EmptyFunctionBlock:
    active: false
  EmptyIfBlock:
    active: false
  EmptyInitBlock:
    active: false
  EmptyKtFile:
    active: false
  EmptySecondaryConstructor:
    active: false
  EmptyTryBlock:
    active: false
  EmptyWhenBlock:
    active: false
  EmptyWhileBlock:
    active: false

exceptions:
  active: false
  ExceptionRaisedInUnexpectedLocation:
    active: false
  InstanceOfCheckForException:
    active: false
  NotImplementedDeclaration:
    active: false
  ObjectExtendsThrowable:
    active: false
  PrintStackTrace:
    active: false
  RethrowCaughtException:
    active: false
  ReturnFromFinally:
    active: false
  SwallowedException:
    active: false
  ThrowingExceptionFromFinally:
    active: false
  ThrowingExceptionInMain:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: false
  ThrowingNewInstanceOfSameException:
    active: false
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: false

formatting:
  active: true
  android: false
  autoCorrect: true
  AnnotationOnSeparateLine:
    active: false
  AnnotationSpacing:
    active: false
  ArgumentListWrapping:
    active: false
  BlockCommentInitialStarAlignment:
    active: false
  ChainWrapping:
    active: true
    autoCorrect: true
  CommentSpacing:
    active: true
    autoCorrect: true
  CommentWrapping:
    active: false
  DiscouragedCommentLocation:
    active: false
  EnumEntryNameCase:
    active: false
  Filename:
    active: false
  FinalNewline:
    active: false
  FunKeywordSpacing:
    active: false
  FunctionTypeReferenceSpacing:
    active: false
  ImportOrdering:
    active: false
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 4
    excludes: [ '**/compose/tokens/**' ]
  KdocWrapping:
    active: false
  MaximumLineLength:
    active: false
  ModifierListSpacing:
    active: false
  ModifierOrdering:
    active: true
    autoCorrect: true
  MultiLineIfElse:
    active: false
  NoBlankLineBeforeRbrace:
    active: true
    autoCorrect: true
    excludes: [ '**/compose/tokens/**', '**/check/BpkDeprecatedTokens.kt' ]
  NoConsecutiveBlankLines:
    active: true
    autoCorrect: true
    excludes: [ '**/compose/tokens/**' ]
  NoEmptyClassBody:
    active: true
    autoCorrect: true
  NoEmptyFirstLineInMethodBlock:
    active: false
  NoLineBreakAfterElse:
    active: true
    autoCorrect: true
  NoLineBreakBeforeAssignment:
    active: true
    autoCorrect: true
  NoMultipleSpaces:
    active: true
    autoCorrect: true
  NoSemicolons:
    active: true
    autoCorrect: true
  NoTrailingSpaces:
    active: true
    autoCorrect: true
  NoUnitReturn:
    active: true
    autoCorrect: true
  NoUnusedImports:
    active: true
    autoCorrect: true
  NoWildcardImports:
    active: true
    packagesToUseImportOnDemandProperty: 'java.util.*,kotlinx.android.synthetic.**'
  PackageName:
    active: true
    autoCorrect: true
    excludes: [ '**/compose/tokens/**' ]
  ParameterListWrapping:
    active: true
    autoCorrect: true
    maxLineLength: 125
  SpacingAroundAngleBrackets:
    active: false
  SpacingAroundColon:
    active: true
    autoCorrect: true
  SpacingAroundComma:
    active: true
    autoCorrect: true
  SpacingAroundCurly:
    active: true
    autoCorrect: true
  SpacingAroundDot:
    active: true
    autoCorrect: true
  SpacingAroundDoubleColon:
    active: false
  SpacingAroundKeyword:
    active: true
    autoCorrect: true
  SpacingAroundOperators:
    active: true
    autoCorrect: true
  SpacingAroundParens:
    active: true
    autoCorrect: true
    excludes: [ '**/compose/tokens/**' ]
  SpacingAroundRangeOperator:
    active: true
    autoCorrect: true
  SpacingAroundUnaryOperator:
    active: false
  SpacingBetweenDeclarationsWithAnnotations:
    active: false
  SpacingBetweenDeclarationsWithComments:
    active: false
  StringTemplate:
    active: true
    autoCorrect: true
  TrailingCommaOnCallSite:
    active: true
    excludes: [ '**/compose/tokens/**' ]
  TrailingCommaOnDeclarationSite:
    active: true
  TypeArgumentListSpacing:
    active: false
  UnnecessaryParenthesesBeforeTrailingLambda:
    active: false
  Wrapping:
    active: false

libraries:
  ForbiddenPublicDataClass:
    active: false
  LibraryCodeMustSpecifyReturnType:
    active: false
  LibraryEntitiesShouldNotBePublic:
    active: false

naming:
  active: false
  BooleanPropertyNaming:
    active: false
  ClassNaming:
    active: false
  ConstructorParameterNaming:
    active: false
  EnumNaming:
    active: false
  ForbiddenClassName:
    active: false
  FunctionMaxLength:
    active: false
  FunctionMinLength:
    active: false
  FunctionNaming:
    active: false
  FunctionParameterNaming:
    active: false
  InvalidPackageDeclaration:
    active: false
  LambdaParameterNaming:
    active: false
  MatchingDeclarationName:
    active: false
  MemberNameEqualsClassName:
    active: false
  NoNameShadowing:
    active: false
  NonBooleanPropertyPrefixedWithIs:
    active: false
  ObjectPropertyNaming:
    active: false
  PackageNaming:
    active: false
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9a-z]*'
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
    privatePropertyPattern: '_?[A-Za-z][_A-Za-z0-9]*'
  VariableMaxLength:
    active: false
  VariableMinLength:
    active: false
  VariableNaming:
    active: false

performance:
  active: false
  ArrayPrimitive:
    active: false
  CouldBeSequence:
    active: false
  ForEachOnRange:
    active: false
  SpreadOperator:
    active: false
  UnnecessaryTemporaryInstantiation:
    active: false

potential-bugs:
  active: false
  AvoidReferentialEquality:
    active: false
  CastToNullableType:
    active: false
  Deprecation:
    active: false
  DontDowncastCollectionTypes:
    active: false
  DoubleMutabilityForCollection:
    active: false
  ElseCaseInsteadOfExhaustiveWhen:
    active: false
  EqualsAlwaysReturnsTrueOrFalse:
    active: false
  EqualsWithHashCodeExist:
    active: false
  ExitOutsideMain:
    active: false
  ExplicitGarbageCollectionCall:
    active: false
  HasPlatformType:
    active: false
  IgnoredReturnValue:
    active: false
  ImplicitDefaultLocale:
    active: false
  ImplicitUnitReturnType:
    active: false
  InvalidRange:
    active: false
  IteratorHasNextCallsNextMethod:
    active: false
  IteratorNotThrowingNoSuchElementException:
    active: false
  LateinitUsage:
    active: false
  MapGetWithNotNullAssertionOperator:
    active: false
  MissingPackageDeclaration:
    active: false
  NullCheckOnMutableProperty:
    active: false
  NullableToStringCall:
    active: false
  UnconditionalJumpStatementInLoop:
    active: false
  UnnecessaryNotNullOperator:
    active: false
  UnnecessarySafeCall:
    active: false
  UnreachableCatchBlock:
    active: false
  UnreachableCode:
    active: false
  UnsafeCallOnNullableType:
    active: false
  UnsafeCast:
    active: false
  UnusedUnaryOperator:
    active: false
  UselessPostfixExpression:
    active: false
  WrongEqualsTypeParameter:
    active: false

style:
  active: false
  CanBeNonNullable:
    active: false
  CascadingCallWrapping:
    active: false
  ClassOrdering:
    active: false
  CollapsibleIfStatements:
    active: false
  DataClassContainsFunctions:
    active: false
  DataClassShouldBeImmutable:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    active: false
  EqualsNullCall:
    active: false
  EqualsOnSignatureLine:
    active: false
  ExplicitCollectionElementAccessMethod:
    active: false
  ExplicitItLambdaParameter:
    active: false
  ExpressionBodySyntax:
    active: false
  ForbiddenComment:
    active: false
  ForbiddenImport:
    active: false
  ForbiddenMethodCall:
    active: false
  ForbiddenSuppress:
    active: false
  ForbiddenVoid:
    active: false
  FunctionOnlyReturningConstant:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  MagicNumber:
    active: false
  MandatoryBracesIfStatements:
    active: false
  MandatoryBracesLoops:
    active: false
  MaxChainedCallsOnSameLine:
    active: false
  MaxLineLength:
    maxLineLength: 125
    excludeCommentStatements: true
  MayBeConst:
    active: false
  ModifierOrder:
    active: false
  MultilineLambdaItParameter:
    active: false
  NestedClassesVisibility:
    active: false
  NewLineAtEndOfFile:
    active: false
  NoTabs:
    active: false
  NullableBooleanCheck:
    active: false
  ObjectLiteralToLambda:
    active: false
  OptionalAbstractKeyword:
    active: false
  OptionalUnit:
    active: false
  OptionalWhenBraces:
    active: false
  PreferToOverPairSyntax:
    active: false
  ProtectedMemberInFinalClass:
    active: false
  RedundantExplicitType:
    active: false
  RedundantHigherOrderMapUsage:
    active: false
  RedundantVisibilityModifierRule:
    active: false
  ReturnCount:
    active: false
  SafeCast:
    active: false
  SerialVersionUIDInSerializableClass:
    active: false
  SpacingBetweenPackageAndImports:
    active: false
  ThrowsCount:
    active: false
  TrailingWhitespace:
    active: false
  UnderscoresInNumericLiterals:
    active: false
  UnnecessaryAbstractClass:
    active: false
  UnnecessaryAnnotationUseSiteTarget:
    active: false
  UnnecessaryApply:
    active: false
  UnnecessaryBackticks:
    active: false
  UnnecessaryFilter:
    active: false
  UnnecessaryInheritance:
    active: false
  UnnecessaryInnerClass:
    active: false
  UnnecessaryLet:
    active: false
  UnnecessaryParentheses:
    active: false
  UntilInsteadOfRangeTo:
    active: false
  UnusedImports:
    active: false
  UnusedPrivateClass:
    active: false
  UnusedPrivateMember:
    active: false
  UseAnyOrNoneInsteadOfFind:
    active: false
  UseArrayLiteralsInAnnotations:
    active: false
  UseCheckNotNull:
    active: false
  UseCheckOrError:
    active: false
  UseDataClass:
    active: false
  UseEmptyCounterpart:
    active: false
  UseIfEmptyOrIfBlank:
    active: false
  UseIfInsteadOfWhen:
    active: false
  UseIsNullOrEmpty:
    active: false
  UseOrEmpty:
    active: false
  UseRequire:
    active: false
  UseRequireNotNull:
    active: false
  UselessCallOnNotNull:
    active: false
  UtilityClassWithPublicConstructor:
    active: false
  VarCouldBeVal:
    active: false
  WildcardImport:
    active: false
