/// Copyright (c) 2015-present, salesforce.com, inc. All rights reserved
/// Licensed under BSD 3-Clause - see LICENSE.txt or git.io/sfdc-license

package com.example.salesforceux.android_sample_app;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.graphics.Rect;
import android.graphics.RectF;

/**
 * Utility for generating Bitmaps from SLDS icons.
 */

public abstract class Icons {

    public static Bitmap getBitmap(Context context, ActionIcons icon, int size) {
        return getBitmap(context, icon, size, context.getResources().getColor(R.color.slds_color_text_icon_default));
    }

    public static Bitmap getBitmap(Context context, ActionIcons icon, int size, int color) {
        Bitmap bmp = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bmp);

        drawIconGlyph(context, icon.value, size, canvas, color);

        return bmp;
    }

    public static Bitmap getBitmap(Context context, CustomIcons icon, int size) {
        return getBitmap(context, icon, size, context.getResources().getColor(R.color.slds_color_text_icon_default));
    }

    public static Bitmap getBitmap(Context context, CustomIcons icon, int size, int color) {
        Bitmap bmp = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bmp);

        drawIconGlyph(context, icon.value, size, canvas, color);

        return bmp;
    }

    public static Bitmap getBitmap(Context context, StandardIcons icon, int size) {
        return getBitmap(context, icon, size, context.getResources().getColor(R.color.slds_color_text_icon_default));
    }

    public static Bitmap getBitmap(Context context, StandardIcons icon, int size, int color) {
        Bitmap bmp = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bmp);

        drawIconGlyph(context, icon.value, size, canvas, color);

        return bmp;
    }

    public static Bitmap getBitmap(Context context, UtilityIcons icon, int size) {
        return getBitmap(context, icon, size, context.getResources().getColor(R.color.slds_color_text_icon_default));
    }

    public static Bitmap getBitmap(Context context, UtilityIcons icon, int size, int color) {
        Bitmap bmp = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bmp);

        drawIconGlyph(context, icon.value, size, canvas, color);

        return bmp;
    }

    private static void drawIconGlyph(Context context, String iconChar, int size, Canvas canvas, int color) {
        Paint textPaint = new Paint();
        textPaint.setFlags(Paint.ANTI_ALIAS_FLAG);
        textPaint.setTextAlign(Paint.Align.CENTER);
        textPaint.setColor(color);
        textPaint.setTextSize(size);
        textPaint.setTypeface(Typeface.createFromAsset(context.getResources().getAssets(), "SalesforceDesignSystemIcons.ttf"));
        float y = (size / 2.0f) - ((textPaint.descent() + textPaint.ascent()) / 2.0f);
        canvas.drawText(iconChar, (size / 2.0f), y, textPaint);
    }

    public enum ActionIcons {
        ActionAddContact ("\uEA01"),
        ActionAddRelationship ("\uEA02"),
        ActionAnnouncement ("\uEA03"),
        ActionApex ("\uEA04"),
        ActionApproval ("\uEA05"),
        ActionBack ("\uEA06"),
        ActionCall ("\uEA07"),
        ActionCanvas ("\uEA08"),
        ActionChangeOwner ("\uEA09"),
        ActionChangeRecordType ("\uEA0A"),
        ActionCheck ("\uEA0B"),
        ActionClone ("\uEA0C"),
        ActionClose ("\uEA0D"),
        ActionDefer ("\uEA0E"),
        ActionDelete ("\uEA0F"),
        ActionDescription ("\uEA10"),
        ActionDialIn ("\uEA11"),
        ActionDownload ("\uEA12"),
        ActionEdit ("\uEA13"),
        ActionEditGroups ("\uEA14"),
        ActionEditRelationship ("\uEA15"),
        ActionEmail ("\uEA16"),
        ActionFallback ("\uEA17"),
        ActionFilter ("\uEA18"),
        ActionFlow ("\uEA19"),
        ActionFollow ("\uEA1A"),
        ActionFollowing ("\uEA1B"),
        ActionFreezeUser ("\uEA1C"),
        ActionGoal ("\uEA1D"),
        ActionGoogleNews ("\uEA1E"),
        ActionInfo ("\uEA1F"),
        ActionJoinGroup ("\uEA20"),
        ActionLeadConvert ("\uEA21"),
        ActionLeaveGroup ("\uEA22"),
        ActionLogACall ("\uEA23"),
        ActionLogEvent ("\uEA24"),
        ActionManagePermSets ("\uEA25"),
        ActionMap ("\uEA26"),
        ActionMore ("\uEA27"),
        ActionNew ("\uEA28"),
        ActionNewAccount ("\uEA29"),
        ActionNewCampaign ("\uEA2A"),
        ActionNewCase ("\uEA2B"),
        ActionNewChildCase ("\uEA2C"),
        ActionNewContact ("\uEA2D"),
        ActionNewCustom1 ("\uEA2E"),
        ActionNewCustom10 ("\uEA2F"),
        ActionNewCustom100 ("\uEA30"),
        ActionNewCustom11 ("\uEA31"),
        ActionNewCustom12 ("\uEA32"),
        ActionNewCustom13 ("\uEA33"),
        ActionNewCustom14 ("\uEA34"),
        ActionNewCustom15 ("\uEA35"),
        ActionNewCustom16 ("\uEA36"),
        ActionNewCustom17 ("\uEA37"),
        ActionNewCustom18 ("\uEA38"),
        ActionNewCustom19 ("\uEA39"),
        ActionNewCustom2 ("\uEA3A"),
        ActionNewCustom20 ("\uEA3B"),
        ActionNewCustom21 ("\uEA3C"),
        ActionNewCustom22 ("\uEA3D"),
        ActionNewCustom23 ("\uEA3E"),
        ActionNewCustom24 ("\uEA3F"),
        ActionNewCustom25 ("\uEA40"),
        ActionNewCustom26 ("\uEA41"),
        ActionNewCustom27 ("\uEA42"),
        ActionNewCustom28 ("\uEA43"),
        ActionNewCustom29 ("\uEA44"),
        ActionNewCustom3 ("\uEA45"),
        ActionNewCustom30 ("\uEA46"),
        ActionNewCustom31 ("\uEA47"),
        ActionNewCustom32 ("\uEA48"),
        ActionNewCustom33 ("\uEA49"),
        ActionNewCustom34 ("\uEA4A"),
        ActionNewCustom35 ("\uEA4B"),
        ActionNewCustom36 ("\uEA4C"),
        ActionNewCustom37 ("\uEA4D"),
        ActionNewCustom38 ("\uEA4E"),
        ActionNewCustom39 ("\uEA4F"),
        ActionNewCustom4 ("\uEA50"),
        ActionNewCustom40 ("\uEA51"),
        ActionNewCustom41 ("\uEA52"),
        ActionNewCustom42 ("\uEA53"),
        ActionNewCustom43 ("\uEA54"),
        ActionNewCustom44 ("\uEA55"),
        ActionNewCustom45 ("\uEA56"),
        ActionNewCustom46 ("\uEA57"),
        ActionNewCustom47 ("\uEA58"),
        ActionNewCustom48 ("\uEA59"),
        ActionNewCustom49 ("\uEA5A"),
        ActionNewCustom5 ("\uEA5B"),
        ActionNewCustom50 ("\uEA5C"),
        ActionNewCustom51 ("\uEA5D"),
        ActionNewCustom52 ("\uEA5E"),
        ActionNewCustom53 ("\uEA5F"),
        ActionNewCustom54 ("\uEA60"),
        ActionNewCustom55 ("\uEA61"),
        ActionNewCustom56 ("\uEA62"),
        ActionNewCustom57 ("\uEA63"),
        ActionNewCustom58 ("\uEA64"),
        ActionNewCustom59 ("\uEA65"),
        ActionNewCustom6 ("\uEA66"),
        ActionNewCustom60 ("\uEA67"),
        ActionNewCustom61 ("\uEA68"),
        ActionNewCustom62 ("\uEA69"),
        ActionNewCustom63 ("\uEA6A"),
        ActionNewCustom64 ("\uEA6B"),
        ActionNewCustom65 ("\uEA6C"),
        ActionNewCustom66 ("\uEA6D"),
        ActionNewCustom67 ("\uEA6E"),
        ActionNewCustom68 ("\uEA6F"),
        ActionNewCustom69 ("\uEA70"),
        ActionNewCustom7 ("\uEA71"),
        ActionNewCustom70 ("\uEA72"),
        ActionNewCustom71 ("\uEA73"),
        ActionNewCustom72 ("\uEA74"),
        ActionNewCustom73 ("\uEA75"),
        ActionNewCustom74 ("\uEA76"),
        ActionNewCustom75 ("\uEA77"),
        ActionNewCustom76 ("\uEA78"),
        ActionNewCustom77 ("\uEA79"),
        ActionNewCustom78 ("\uEA7A"),
        ActionNewCustom79 ("\uEA7B"),
        ActionNewCustom8 ("\uEA7C"),
        ActionNewCustom80 ("\uEA7D"),
        ActionNewCustom81 ("\uEA7E"),
        ActionNewCustom82 ("\uEA7F"),
        ActionNewCustom83 ("\uEA80"),
        ActionNewCustom84 ("\uEA81"),
        ActionNewCustom85 ("\uEA82"),
        ActionNewCustom86 ("\uEA83"),
        ActionNewCustom87 ("\uEA84"),
        ActionNewCustom88 ("\uEA85"),
        ActionNewCustom89 ("\uEA86"),
        ActionNewCustom9 ("\uEA87"),
        ActionNewCustom90 ("\uEA88"),
        ActionNewCustom91 ("\uEA89"),
        ActionNewCustom92 ("\uEA8A"),
        ActionNewCustom93 ("\uEA8B"),
        ActionNewCustom94 ("\uEA8C"),
        ActionNewCustom95 ("\uEA8D"),
        ActionNewCustom96 ("\uEA8E"),
        ActionNewCustom97 ("\uEA8F"),
        ActionNewCustom98 ("\uEA90"),
        ActionNewCustom99 ("\uEA91"),
        ActionNewEvent ("\uEA92"),
        ActionNewGroup ("\uEA93"),
        ActionNewLead ("\uEA94"),
        ActionNewNote ("\uEA95"),
        ActionNewNotebook ("\uEA96"),
        ActionNewOpportunity ("\uEA97"),
        ActionNewPersonAccount ("\uEA98"),
        ActionNewTask ("\uEA99"),
        ActionPasswordUnlock ("\uEA9A"),
        ActionPreview ("\uEA9B"),
        ActionPriority ("\uEA9C"),
        ActionQuestionPostAction ("\uEA9D"),
        ActionQuote ("\uEA9E"),
        ActionRecord ("\uEA9F"),
        ActionRefresh ("\uEAA0"),
        ActionReject ("\uEAA1"),
        ActionRemove ("\uEAA2"),
        ActionRemoveRelationship ("\uEAA3"),
        ActionResetPassword ("\uEAA4"),
        ActionShare ("\uEAA5"),
        ActionShareFile ("\uEAA6"),
        ActionShareLink ("\uEAA7"),
        ActionSharePoll ("\uEAA8"),
        ActionSharePost ("\uEAA9"),
        ActionShareThanks ("\uEAAA"),
        ActionSort ("\uEAAB"),
        ActionSubmitForApproval ("\uEAAC"),
        ActionUpdate ("\uEAAD"),
        ActionUpdateStatus ("\uEAAE"),
        ActionUpload ("\uEAAF"),
        ActionUser ("\uEAB0"),
        ActionUserActivation ("\uEAB1"),
        ActionViewRelationship ("\uEAB2"),
        ActionWebLink ("\uEAB3");

        final String value;
        ActionIcons(String value) { this.value = value; }
    }

    public enum CustomIcons {
        Custom1 ("\uEAB4"),
        Custom10 ("\uEAB5"),
        Custom100 ("\uEAB6"),
        Custom101 ("\uEAB7"),
        Custom102 ("\uEAB8"),
        Custom103 ("\uEAB9"),
        Custom104 ("\uEABA"),
        Custom105 ("\uEABB"),
        Custom106 ("\uEABC"),
        Custom107 ("\uEABD"),
        Custom108 ("\uEABE"),
        Custom109 ("\uEABF"),
        Custom11 ("\uEAC0"),
        Custom110 ("\uEAC1"),
        Custom111 ("\uEAC2"),
        Custom112 ("\uEAC3"),
        Custom113 ("\uEAC4"),
        Custom12 ("\uEAC5"),
        Custom13 ("\uEAC6"),
        Custom14 ("\uEAC7"),
        Custom15 ("\uEAC8"),
        Custom16 ("\uEAC9"),
        Custom17 ("\uEACA"),
        Custom18 ("\uEACB"),
        Custom19 ("\uEACC"),
        Custom2 ("\uEACD"),
        Custom20 ("\uEACE"),
        Custom21 ("\uEACF"),
        Custom22 ("\uEAD0"),
        Custom23 ("\uEAD1"),
        Custom24 ("\uEAD2"),
        Custom25 ("\uEAD3"),
        Custom26 ("\uEAD4"),
        Custom27 ("\uEAD5"),
        Custom28 ("\uEAD6"),
        Custom29 ("\uEAD7"),
        Custom3 ("\uEAD8"),
        Custom30 ("\uEAD9"),
        Custom31 ("\uEADA"),
        Custom32 ("\uEADB"),
        Custom33 ("\uEADC"),
        Custom34 ("\uEADD"),
        Custom35 ("\uEADE"),
        Custom36 ("\uEADF"),
        Custom37 ("\uEAE0"),
        Custom38 ("\uEAE1"),
        Custom39 ("\uEAE2"),
        Custom4 ("\uEAE3"),
        Custom40 ("\uEAE4"),
        Custom41 ("\uEAE5"),
        Custom42 ("\uEAE6"),
        Custom43 ("\uEAE7"),
        Custom44 ("\uEAE8"),
        Custom45 ("\uEAE9"),
        Custom46 ("\uEAEA"),
        Custom47 ("\uEAEB"),
        Custom48 ("\uEAEC"),
        Custom49 ("\uEAED"),
        Custom5 ("\uEAEE"),
        Custom50 ("\uEAEF"),
        Custom51 ("\uEAF0"),
        Custom52 ("\uEAF1"),
        Custom53 ("\uEAF2"),
        Custom54 ("\uEAF3"),
        Custom55 ("\uEAF4"),
        Custom56 ("\uEAF5"),
        Custom57 ("\uEAF6"),
        Custom58 ("\uEAF7"),
        Custom59 ("\uEAF8"),
        Custom6 ("\uEAF9"),
        Custom60 ("\uEAFA"),
        Custom61 ("\uEAFB"),
        Custom62 ("\uEAFC"),
        Custom63 ("\uEAFD"),
        Custom64 ("\uEAFE"),
        Custom65 ("\uEAFF"),
        Custom66 ("\uEB00"),
        Custom67 ("\uEB01"),
        Custom68 ("\uEB02"),
        Custom69 ("\uEB03"),
        Custom7 ("\uEB04"),
        Custom70 ("\uEB05"),
        Custom71 ("\uEB06"),
        Custom72 ("\uEB07"),
        Custom73 ("\uEB08"),
        Custom74 ("\uEB09"),
        Custom75 ("\uEB0A"),
        Custom76 ("\uEB0B"),
        Custom77 ("\uEB0C"),
        Custom78 ("\uEB0D"),
        Custom79 ("\uEB0E"),
        Custom8 ("\uEB0F"),
        Custom80 ("\uEB10"),
        Custom81 ("\uEB11"),
        Custom82 ("\uEB12"),
        Custom83 ("\uEB13"),
        Custom84 ("\uEB14"),
        Custom85 ("\uEB15"),
        Custom86 ("\uEB16"),
        Custom87 ("\uEB17"),
        Custom88 ("\uEB18"),
        Custom89 ("\uEB19"),
        Custom9 ("\uEB1A"),
        Custom90 ("\uEB1B"),
        Custom91 ("\uEB1C"),
        Custom92 ("\uEB1D"),
        Custom93 ("\uEB1E"),
        Custom94 ("\uEB1F"),
        Custom95 ("\uEB20"),
        Custom96 ("\uEB21"),
        Custom97 ("\uEB22"),
        Custom98 ("\uEB23"),
        Custom99 ("\uEB24");

        final String value;
        CustomIcons(String value) { this.value = value; }
    }

    public enum StandardIcons {
        StandardAccount ("\uEB25"),
        StandardAddress ("\uEB26"),
        StandardAnnouncement ("\uEB27"),
        StandardAnswerBest ("\uEB28"),
        StandardAnswerPrivate ("\uEB29"),
        StandardAnswerPublic ("\uEB2A"),
        StandardApproval ("\uEB2B"),
        StandardApps ("\uEB2C"),
        StandardAppsAdmin ("\uEB2D"),
        StandardArticle ("\uEB2E"),
        StandardAssignedResource ("\uEB2F"),
        StandardAvatar ("\uEB30"),
        StandardAvatarLoading ("\uEB31"),
        StandardCalibration ("\uEB32"),
        StandardCall ("\uEB33"),
        StandardCallHistory ("\uEB34"),
        StandardCampaign ("\uEB35"),
        StandardCampaignMembers ("\uEB36"),
        StandardCanvas ("\uEB37"),
        StandardCarousel ("\uEB38"),
        StandardCase ("\uEB39"),
        StandardCaseChangeStatus ("\uEB3A"),
        StandardCaseComment ("\uEB3B"),
        StandardCaseEmail ("\uEB3C"),
        StandardCaseLogACall ("\uEB3D"),
        StandardCaseTranscript ("\uEB3E"),
        StandardClient ("\uEB3F"),
        StandardCoaching ("\uEB40"),
        StandardConnectedApps ("\uEB41"),
        StandardContact ("\uEB42"),
        StandardContract ("\uEB43"),
        StandardCustom ("\uEB44"),
        StandardCustomNotification ("\uEB45"),
        StandardDashboard ("\uEB46"),
        StandardDatadotcom ("\uEB47"),
        StandardDefault ("\uEB48"),
        StandardDocument ("\uEB49"),
        StandardDrafts ("\uEB4A"),
        StandardEmail ("\uEB4B"),
        StandardEmailChatter ("\uEB4C"),
        StandardEmpty ("\uEB4D"),
        StandardEndorsement ("\uEB4E"),
        StandardEnvironmentHub ("\uEB4F"),
        StandardEvent ("\uEB50"),
        StandardFeed ("\uEB51"),
        StandardFeedback ("\uEB52"),
        StandardFile ("\uEB53"),
        StandardFlow ("\uEB54"),
        StandardFolder ("\uEB55"),
        StandardForecasts ("\uEB56"),
        StandardGenericLoading ("\uEB57"),
        StandardGoals ("\uEB58"),
        StandardGroupLoading ("\uEB59"),
        StandardGroups ("\uEB5A"),
        StandardHierarchy ("\uEB5B"),
        StandardHome ("\uEB5C"),
        StandardHousehold ("\uEB5D"),
        StandardInsights ("\uEB5E"),
        StandardInvestmentAccount ("\uEB5F"),
        StandardLead ("\uEB60"),
        StandardLink ("\uEB61"),
        StandardLocation ("\uEB62"),
        StandardLogACall ("\uEB63"),
        StandardMarketingActions ("\uEB64"),
        StandardMerge ("\uEB65"),
        StandardMetrics ("\uEB66"),
        StandardNews ("\uEB67"),
        StandardNote ("\uEB68"),
        StandardOperatingHours ("\uEB69"),
        StandardOpportunity ("\uEB6A"),
        StandardOrders ("\uEB6B"),
        StandardPeople ("\uEB6C"),
        StandardPerformance ("\uEB6D"),
        StandardPersonAccount ("\uEB6E"),
        StandardPhoto ("\uEB6F"),
        StandardPoll ("\uEB70"),
        StandardPortal ("\uEB71"),
        StandardPost ("\uEB72"),
        StandardPricebook ("\uEB73"),
        StandardProcess ("\uEB74"),
        StandardProduct ("\uEB75"),
        StandardProductConsumed ("\uEB76"),
        StandardProductItem ("\uEB77"),
        StandardProductItemTransaction ("\uEB78"),
        StandardProductRequired ("\uEB79"),
        StandardProductTransfer ("\uEB7A"),
        StandardQuestionBest ("\uEB7B"),
        StandardQuestionFeed ("\uEB7C"),
        StandardQuotes ("\uEB7D"),
        StandardRecent ("\uEB7E"),
        StandardRecord ("\uEB7F"),
        StandardRelatedList ("\uEB80"),
        StandardRelationship ("\uEB81"),
        StandardReport ("\uEB82"),
        StandardResourceAbsence ("\uEB83"),
        StandardResourceCapacity ("\uEB84"),
        StandardResourcePreference ("\uEB85"),
        StandardResourceSkill ("\uEB86"),
        StandardReward ("\uEB87"),
        StandardRtcPresence ("\uEB88"),
        StandardSalesPath ("\uEB89"),
        StandardScanCard ("\uEB8A"),
        StandardServiceAppointment ("\uEB8B"),
        StandardServiceContract ("\uEB8C"),
        StandardServiceReport ("\uEB8D"),
        StandardServiceResource ("\uEB8E"),
        StandardServiceTerritory ("\uEB8F"),
        StandardServiceTerritoryMember ("\uEB90"),
        StandardSkill ("\uEB91"),
        StandardSkillEntity ("\uEB92"),
        StandardSkillRequirement ("\uEB93"),
        StandardSocial ("\uEB94"),
        StandardSolution ("\uEB95"),
        StandardSossession ("\uEB96"),
        StandardTask ("\uEB97"),
        StandardTask2 ("\uEB98"),
        StandardTeamMember ("\uEB99"),
        StandardThanks ("\uEB9A"),
        StandardThanksLoading ("\uEB9B"),
        StandardTimeslot ("\uEB9C"),
        StandardToday ("\uEB9D"),
        StandardTopic ("\uEB9E"),
        StandardUnmatched ("\uEB9F"),
        StandardUser ("\uEBA0"),
        StandardWorkOrder ("\uEBA1"),
        StandardWorkOrderItem ("\uEBA2"),
        StandardWorkType ("\uEBA3");

        final String value;
        StandardIcons(String value) { this.value = value; }
    }

    public enum UtilityIcons {
        UtilityAdd ("\uEBA4"),
        UtilityAdduser ("\uEBA5"),
        UtilityAnnouncement ("\uEBA6"),
        UtilityAnswer ("\uEBA7"),
        UtilityApex ("\uEBA8"),
        UtilityApproval ("\uEBA9"),
        UtilityApps ("\uEBAA"),
        UtilityArrowdown ("\uEBAB"),
        UtilityArrowup ("\uEBAC"),
        UtilityAttach ("\uEBAD"),
        UtilityBack ("\uEBAE"),
        UtilityBan ("\uEBAF"),
        UtilityBold ("\uEBB0"),
        UtilityBookmark ("\uEBB1"),
        UtilityBreadcrumbs ("\uEBB2"),
        UtilityBroadcast ("\uEBB3"),
        UtilityBrush ("\uEBB4"),
        UtilityBucket ("\uEBB5"),
        UtilityBuilder ("\uEBB6"),
        UtilityCall ("\uEBB7"),
        UtilityCapslock ("\uEBB8"),
        UtilityCases ("\uEBB9"),
        UtilityCenterAlignText ("\uEBBA"),
        UtilityChangeOwner ("\uEBBB"),
        UtilityChangeRecordType ("\uEBBC"),
        UtilityChart ("\uEBBD"),
        UtilityChat ("\uEBBE"),
        UtilityCheck ("\uEBBF"),
        UtilityCheckin ("\uEBC0"),
        UtilityChevrondown ("\uEBC1"),
        UtilityChevronleft ("\uEBC2"),
        UtilityChevronright ("\uEBC3"),
        UtilityChevronup ("\uEBC4"),
        UtilityClear ("\uEBC5"),
        UtilityClock ("\uEBC6"),
        UtilityClose ("\uEBC7"),
        UtilityComments ("\uEBC8"),
        UtilityCompany ("\uEBC9"),
        UtilityConnectedApps ("\uEBCA"),
        UtilityContract ("\uEBCB"),
        UtilityContractAlt ("\uEBCC"),
        UtilityCopy ("\uEBCD"),
        UtilityCrossfilter ("\uEBCE"),
        UtilityCustomApps ("\uEBCF"),
        UtilityCut ("\uEBD0"),
        UtilityDash ("\uEBD1"),
        UtilityDatabase ("\uEBD2"),
        UtilityDatadotcom ("\uEBD3"),
        UtilityDayview ("\uEBD4"),
        UtilityDelete ("\uEBD5"),
        UtilityDeprecate ("\uEBD6"),
        UtilityDescription ("\uEBD7"),
        UtilityDesktop ("\uEBD8"),
        UtilityDislike ("\uEBD9"),
        UtilityDockPanel ("\uEBDA"),
        UtilityDown ("\uEBDB"),
        UtilityDownload ("\uEBDC"),
        UtilityEdit ("\uEBDD"),
        UtilityEditForm ("\uEBDE"),
        UtilityEmail ("\uEBDF"),
        UtilityEmoji ("\uEBE0"),
        UtilityEndCall ("\uEBE1"),
        UtilityErectWindow ("\uEBE2"),
        UtilityError ("\uEBE3"),
        UtilityEvent ("\uEBE4"),
        UtilityExpand ("\uEBE5"),
        UtilityExpandAlt ("\uEBE6"),
        UtilityFallback ("\uEBE7"),
        UtilityFavorite ("\uEBE8"),
        UtilityFeed ("\uEBE9"),
        UtilityFile ("\uEBEA"),
        UtilityFilter ("\uEBEB"),
        UtilityFilterList ("\uEBEC"),
        UtilityFlow ("\uEBED"),
        UtilityForward ("\uEBEE"),
        UtilityFrozen ("\uEBEF"),
        UtilityFullWidthView ("\uEBF0"),
        UtilityGroups ("\uEBF1"),
        UtilityHelp ("\uEBF2"),
        UtilityHome ("\uEBF3"),
        UtilityIdentity ("\uEBF4"),
        UtilityImage ("\uEBF5"),
        UtilityInbox ("\uEBF6"),
        UtilityInfo ("\uEBF7"),
        UtilityInfoAlt ("\uEBF8"),
        UtilityInsertTagField ("\uEBF9"),
        UtilityInsertTemplate ("\uEBFA"),
        UtilityItalic ("\uEBFB"),
        UtilityJumpToBottom ("\uEBFC"),
        UtilityJumpToTop ("\uEBFD"),
        UtilityJustifyText ("\uEBFE"),
        UtilityKanban ("\uEBFF"),
        UtilityKeyboardDismiss ("\uEC00"),
        UtilityKnowledgeBase ("\uEC01"),
        UtilityLayers ("\uEC02"),
        UtilityLayout ("\uEC03"),
        UtilityLeft ("\uEC04"),
        UtilityLeftAlignText ("\uEC05"),
        UtilityLevelUp ("\uEC06"),
        UtilityLightBulb ("\uEC07"),
        UtilityLike ("\uEC08"),
        UtilityLink ("\uEC09"),
        UtilityList ("\uEC0A"),
        UtilityLocation ("\uEC0B"),
        UtilityLock ("\uEC0C"),
        UtilityLogACall ("\uEC0D"),
        UtilityLogout ("\uEC0E"),
        UtilityMagicwand ("\uEC0F"),
        UtilityMarkAllAsRead ("\uEC10"),
        UtilityMatrix ("\uEC11"),
        UtilityMerge ("\uEC12"),
        UtilityMetrics ("\uEC13"),
        UtilityMinimizeWindow ("\uEC14"),
        UtilityMoneybag ("\uEC15"),
        UtilityMonthlyview ("\uEC16"),
        UtilityMove ("\uEC17"),
        UtilityMuted ("\uEC18"),
        UtilityNew ("\uEC19"),
        UtilityNewDirectMessage ("\uEC1A"),
        UtilityNewWindow ("\uEC1B"),
        UtilityNews ("\uEC1C"),
        UtilityNote ("\uEC1D"),
        UtilityNotebook ("\uEC1E"),
        UtilityNotification ("\uEC1F"),
        UtilityOffice365 ("\uEC20"),
        UtilityOffline ("\uEC21"),
        UtilityOfflineCached ("\uEC22"),
        UtilityOpen ("\uEC23"),
        UtilityOpenFolder ("\uEC24"),
        UtilityOpenedFolder ("\uEC25"),
        UtilityOverflow ("\uEC26"),
        UtilityPackage ("\uEC27"),
        UtilityPackageOrg ("\uEC28"),
        UtilityPackageOrgBeta ("\uEC29"),
        UtilityPage ("\uEC2A"),
        UtilityPalette ("\uEC2B"),
        UtilityPaste ("\uEC2C"),
        UtilityPeople ("\uEC2D"),
        UtilityPhoneLandscape ("\uEC2E"),
        UtilityPhonePortrait ("\uEC2F"),
        UtilityPhoto ("\uEC30"),
        UtilityPicklist ("\uEC31"),
        UtilityPower ("\uEC32"),
        UtilityPreview ("\uEC33"),
        UtilityPriority ("\uEC34"),
        UtilityProcess ("\uEC35"),
        UtilityPush ("\uEC36"),
        UtilityPuzzle ("\uEC37"),
        UtilityQuestion ("\uEC38"),
        UtilityQuestionsAndAnswers ("\uEC39"),
        UtilityQuotationMarks ("\uEC3A"),
        UtilityRecord ("\uEC3B"),
        UtilityRecordCreate ("\uEC3C"),
        UtilityRedo ("\uEC3D"),
        UtilityRefresh ("\uEC3E"),
        UtilityRelate ("\uEC3F"),
        UtilityRemoveFormatting ("\uEC40"),
        UtilityRemoveLink ("\uEC41"),
        UtilityReplace ("\uEC42"),
        UtilityReply ("\uEC43"),
        UtilityReplyAll ("\uEC44"),
        UtilityResetPassword ("\uEC45"),
        UtilityResourceAbsence ("\uEC46"),
        UtilityResourceCapacity ("\uEC47"),
        UtilityResourceTerritory ("\uEC48"),
        UtilityRetweet ("\uEC49"),
        UtilityRichtextbulletedlist ("\uEC4A"),
        UtilityRichtextindent ("\uEC4B"),
        UtilityRichtextnumberedlist ("\uEC4C"),
        UtilityRichtextoutdent ("\uEC4D"),
        UtilityRight ("\uEC4E"),
        UtilityRightAlignText ("\uEC4F"),
        UtilityRotate ("\uEC50"),
        UtilityRows ("\uEC51"),
        UtilitySalesforce1 ("\uEC52"),
        UtilitySearch ("\uEC53"),
        UtilitySettings ("\uEC54"),
        UtilitySetup ("\uEC55"),
        UtilitySetupAssistantGuide ("\uEC56"),
        UtilityShare ("\uEC57"),
        UtilityShareMobile ("\uEC58"),
        UtilitySharePost ("\uEC59"),
        UtilityShield ("\uEC5A"),
        UtilitySideList ("\uEC5B"),
        UtilitySignpost ("\uEC5C"),
        UtilitySms ("\uEC5D"),
        UtilitySnippet ("\uEC5E"),
        UtilitySocialshare ("\uEC5F"),
        UtilitySort ("\uEC60"),
        UtilitySpinner ("\uEC61"),
        UtilityStandardObjects ("\uEC62"),
        UtilityStop ("\uEC63"),
        UtilityStrikethrough ("\uEC64"),
        UtilitySuccess ("\uEC65"),
        UtilitySummary ("\uEC66"),
        UtilitySummarydetail ("\uEC67"),
        UtilitySwitch ("\uEC68"),
        UtilitySync ("\uEC69"),
        UtilityTable ("\uEC6A"),
        UtilityTabletLandscape ("\uEC6B"),
        UtilityTabletPortrait ("\uEC6C"),
        UtilityTabset ("\uEC6D"),
        UtilityTask ("\uEC6E"),
        UtilityTextBackgroundColor ("\uEC6F"),
        UtilityTextColor ("\uEC70"),
        UtilityThreedots ("\uEC71"),
        UtilityThreedotsVertical ("\uEC72"),
        UtilityThunder ("\uEC73"),
        UtilityTileCardList ("\uEC74"),
        UtilityTopic ("\uEC75"),
        UtilityTouchAction ("\uEC76"),
        UtilityTrail ("\uEC77"),
        UtilityTrending ("\uEC78"),
        UtilityTurnOffNotifications ("\uEC79"),
        UtilityTypeTool ("\uEC7A"),
        UtilityUndelete ("\uEC7B"),
        UtilityUndeprecate ("\uEC7C"),
        UtilityUnderline ("\uEC7D"),
        UtilityUndo ("\uEC7E"),
        UtilityUnlock ("\uEC7F"),
        UtilityUnmuted ("\uEC80"),
        UtilityUp ("\uEC81"),
        UtilityUpload ("\uEC82"),
        UtilityUser ("\uEC83"),
        UtilityUserRole ("\uEC84"),
        UtilityVideo ("\uEC85"),
        UtilityVolumeHigh ("\uEC86"),
        UtilityVolumeLow ("\uEC87"),
        UtilityVolumeOff ("\uEC88"),
        UtilityWarning ("\uEC89"),
        UtilityWeeklyview ("\uEC8A"),
        UtilityWifi ("\uEC8B"),
        UtilityWorkOrderType ("\uEC8C"),
        UtilityWorld ("\uEC8D"),
        UtilityYubiKey ("\uEC8E"),
        UtilityZoomin ("\uEC8F"),
        UtilityZoomout ("\uEC90");

        final String value;
        UtilityIcons(String value) { this.value = value; }
    }


}