/**
 * Backpack for Android - Skyscanner's Design System
 *
 * Copyright 2018 - 2026 Skyscanner Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.skyscanner.backpack.lint

import com.google.common.io.Resources
import net.skyscanner.backpack.tokens.Pipeline
import java.io.File
import java.nio.charset.StandardCharsets

/**
 * Output handlers for lint rule generation files.
 * Similar to BpkOutput but specific to lint detector code generation.
 */
sealed class BpkLintingOutput<Input> : (Input) -> Boolean {

    data class KotlinFile(
        val srcDir: String,
        val pkg: String,
        val name: String,
    ) : BpkLintingOutput<String>() {

        override fun invoke(content: String): Boolean {
            // Get copyright from buildSrc resources
            val copyright = try {
                Resources.toString(Resources.getResource("copyright.txt"), StandardCharsets.UTF_8)
            } catch (e: Exception) {
                throw IllegalStateException(
                    "Failed to load copyright header from buildSrc/src/main/resources/copyright.txt. " +
                        "Copyright headers are required for all generated files.",
                    e,
                )
            }

            // Add auto-generated comment
            val autoGeneratedComment = "// Auto-generated: do not edit\n\n"

            // Write to target file with copyright header and auto-generated comment
            val targetDir = File(srcDir, pkg.replace('.', '/'))
            targetDir.mkdirs()
            val targetFile = File(targetDir, name)
            targetFile.writeText(copyright + autoGeneratedComment + content)

            println("Generated: ${targetFile.absolutePath}")
            return true
        }
    }
}

/**
 * Extension function to save Pipeline output to BpkLintingOutput.
 * Similar to saveTo for BpkOutput but for lint generation.
 */
fun <T> Pipeline<T>.saveToLint(output: BpkLintingOutput<T>): Pipeline<Boolean> =
    object : Pipeline<Boolean> {
        override fun execute(): Boolean = output(this@saveToLint.execute())
    }
