/**
 * Backpack for Android - Skyscanner's Design System
 *
 * Copyright 2018 - 2025 Skyscanner Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This module is a passive container for generated icon drawable resources.
// The actual icon generation is handled by the generateInternalIcons task
// in backpack-common/tokens.gradle.kts which generates the drawable XML files
// from SVG sources and places them in this module's drawable-nodpi directory.

tasks {
    val group = "tokens"

    // This module doesn't generate its own tokens but serves as a container
    // for drawable resources generated by the backpack-common module
    val generateTokens by registering {
        this.group = group
        // No actual generation needed - resources are generated by backpack-common
    }
}
