#!/usr/bin/env node
/**
 * Backpack for Android - Skyscanner's Design System
 *
 * Copyright 2018-2020 Skyscanner Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const fs = require('fs');
const child_process = require('child_process');
const {
  promisify
} = require("util");
const {
  exec
} = require('child_process');
const execAsync = promisify(exec);

const [node, path, releaseTag, ...rest] = process.argv;

const exitOnError = (err) => {
  if(err) {
    console.log(err);
    process.exit(1);
  }
}

const buildDocs = () => {
  fs.mkdirSync(`./dist`, exitOnError);

  fs.mkdirSync(`./dist/versions`, exitOnError);

  fs.mkdirSync(`./dist/versions/${releaseTag}`, exitOnError);

  fs.mkdirSync(`./dist/versions/latest`, exitOnError);

  child_process.execSync(`npm run docs -- -PdokkaOutput=./dist/versions/`, exitOnError);

  fs.renameSync('./dist/versions/backpack-android', `./dist/versions/${releaseTag}`, exitOnError);

  fs.writeFile(`dist/404.html`,
`<!DOCTYPE html>
<html>
  <meta http-equiv="refresh" content="1;url=/android/versions/${releaseTag}" />
  <script type="text/javascript">
    const androidDocsPath = (window.location + '').split('android/versions/latest');
    if (androidDocsPath.length > 1) {
      window.location = \`/android/versions/${releaseTag}\${androidDocsPath[1]}\`;
    }
  </script>
</html>
`, { flag: 'w' }, exitOnError);

  fs.writeFile(`dist/index.html`,
`<!DOCTYPE html>
<html>
  <meta http-equiv="refresh" content="0;url=/android/versions/${releaseTag}" />
</html>
`, { flag: 'w' }, exitOnError);

  fs.writeFile(`dist/versions/latest/index.html`,
`<!DOCTYPE html>
<html>
  <meta http-equiv="refresh" content="0;url=/android/versions/${releaseTag}" />
</html>
`, { flag: 'w' }, exitOnError);
}

buildDocs();

