#!/usr/bin/env node

const { promisify } = require('util');
const { exec } = require('child_process');

const execAsync = promisify(exec);

const command = "git status --porcelain | awk '{print $2}'";
const [...filesToIgnore] = process.argv;

const exists = item => !!item;

const isNotInList = list => item => list.indexOf(item) === -1;

const init = async () => {
  const { stdout } = await execAsync(command, {
    cwd: `${__dirname}/../`,
  });
  const changedFiles = stdout
    .trim()
    .split('\n')
    .filter(isNotInList(filesToIgnore))
    .filter(exists);

  if (changedFiles.length) {
    const changedFilesLog = changedFiles.join(',');
    const ignoredFilesLog = filesToIgnore.join(',');
    console.log(
      `😰  Git shows some files have been changed. Changed files: ${changedFilesLog}. (ignoring ${ignoredFilesLog})`,
    );

    const { stdout: diff } = await execAsync('git --no-pager diff', {
      cwd: `${__dirname}/../`,
    });

    console.log(diff);
    process.exit(1);
  }
};

init();
