name: Butler

on:
  pull_request:
    branches: [main]
    types: [labeled, opened]

defaults:
  run:
    shell: bash -l {0}

env:
  api-level: 24

jobs:
  
  screenshots:
    name: screenshots-update
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'screenshots-update' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NPM
        run: |
          nvm install

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ env.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: google_apis
          profile: Nexus 4
          sdcard-path-or-size: 512M
          api-level: ${{ env.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Record Screenshots
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: google_apis
          profile: Nexus 4
          sdcard-path-or-size: 512M
          api-level: ${{ env.api-level }}
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            ./scripts/record_screenshot_tests.sh
      
      - name: Update repository
        run: |
          git config --local user.email "31124577+backpackbot@users.noreply.github.com"
          git config --local user.name "Backpack Bot"
          git commit -am "Update screenshots"