name: Deploy

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash -l {0}

jobs:

  Build:
    name: Build
    uses: ./.github/workflows/build.yml

  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [Build]
    timeout-minutes: 30

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Trigger backpack.github.io CI
        run: |
          curl -f -s -X POST -H "Content-Type: application/json" -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" -d "{\"ref\":\"main\",\"inputs\":{\"repo\":\"backpack-android\"}}" https://api.github.com/repos/Skyscanner/backpack-docs/actions/workflows/ci.yml/dispatches
        env:
          GITHUB_TOKEN: ${{ secrets.BACKPACK_DOCS_DEPLOY_TOKEN }}
