name: label-check

on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label-check:
    runs-on: ubuntu-latest

    steps:
      - uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'major, minor, patch, dependencies, skip-changelog'
          pull-request-number: '${{ github.event.pull_request.number }}'
