name: label-check

on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label-check:
    runs-on: ubuntu-24.04-16cores-public

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major,minor,patch,dependencies,skip-changelog
          repo_token: ${{ steps.app-token.outputs.token }}
