name: PR Documentation Test

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'docs/**'
      - 'Backpack/**'
      - 'backpack-compose/**'
      - 'backpack-common/**'
      - 'build.gradle'
      - 'dokka.gradle'
      - '.github/workflows/release.yml'
      - '.github/workflows/pr-docs-test.yml'

defaults:
  run:
    shell: bash -l {0}

env:
  flavour: oss

jobs:
  test-docs:
    name: Test Documentation Generation
    runs-on: ubuntu-24.04-16cores-public
    timeout-minutes: 30
    permissions:
        contents: read
        packages: read
        pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Dokka docs and prepare documentation
        run: ./gradlew prepareDocs

      - name: Deploy test documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_KEY }}
          publish_dir: dokka/
          keep_files: false
          external_repository: backpack/android
          publish_branch: main
          force_orphan: true

